### ISSUE TITLE
Custom training don't work

### ISSUE THREAD

**Issue by xcbtrader** [OlafenwaMoses/ImageAI#142]
Hello.
I follow the instructions for a training custom model but don't work.
I see more information in the console but crash in the first epoch.
Windows 10, GPU NVIDIA GEFORCE GTX

error:
2019-01-13 10:46:22.750440: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ***************************************************************************************************x
2019-01-13 10:46:22.755758: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at transpose_op.cc:199 : Resource exhausted: OOM when allocating tensor with shape[32,28,28,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

and at the end:
---------------------------------------------------------------------------------------------------------
2019-01-13 10:46:58.546045: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ****************************************************************************************************
2019-01-13 10:46:58.551540: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at conv_ops.cc:446 : Resource exhausted: OOM when allocating tensor with shape[32,512,28,28] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "imageai_train.py", line 5, in <module>
    model_trainer.trainModel(num_objects=2, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=False)
  File "C:\Users\Xavier\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 249, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler])
  File "C:\Users\Xavier\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2177, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Xavier\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 176, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "C:\Users\Xavier\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1940, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\Xavier\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\python\keras\backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "C:\Users\Xavier\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\Xavier\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,28,28,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/Adam/gradients/zeros_192-0-1-TransposeNCHWToNHWC-LayoutOptimizer}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/zeros_192, PermConstNCHWToNHWC-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss/mul/_1999}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_20026_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by OlafenwaMoses** [comment]
Refer to this discussion.

**Comment by rola93** [comment]
was this issue solved? If it was, please, close the issue.

Otherwise, you can try using a smaller batch_size and upgrading ImageAI
